In [1]:
# Cleaning Data

In [2]:
import pandas as pd
df = pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [3]:
# Cleaning null values
df.isnull() # Can also use isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [4]:
df.isnull().sum() # To count no of null values per column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [5]:
df.dropna() # To remove null values containing rows, if you write axis = 1 in the brackets it will drop the columns with null values

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [6]:
cleaned_data = df.copy()
cleaned_data["age"] = cleaned_data["age"].fillna(cleaned_data["age"].mean()) #To fill the na values with some particular one.
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [7]:
# ffill() and bfill()
# The basic concept is in ffill() whenever you get a null value, you simply copy the previous value into it(think of it as moving in a top to down direction). 
# The reverse happens in bfill()

In [8]:
# Handling duplicate values
df.duplicated() #To check duplicated values

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [9]:
df2 = df.copy()
df2.drop_duplicates(inplace = True) #This is to drop duplicate values, inplace makes the actual change in the original data instead of giving a view.
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
# Handling data types

In [11]:
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [12]:
cleaned_data["age"] = cleaned_data["age"].astype("int64")
cleaned_data["age"].dtypes

dtype('int64')

In [13]:
# Handling date time data

air = pd.read_csv("globalAirQuality.csv")
air.sample(3)

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
14699,2025-11-17 05:25:17.554219,PH,Manila,14.600,120.984,30.560,45.874,28.590,7.759,75.484,0.991,71,5.830,71.929,7.230
15524,2025-11-06 14:25:17.554219,US,Chicago,41.878,-87.630,59.523,71.008,35.346,5.493,41.952,0.884,119,32.250,70.219,9.246
5253,2025-11-13 15:25:17.554219,NG,Lagos,6.524,3.379,49.394,81.615,22.534,6.824,19.531,0.556,98,13.976,87.051,0.733

In [14]:
date = pd.to_datetime("2026-12-31")
type(date) # We don't use dtypes here since timestamp does not have that function.

pandas._libs.tslibs.timestamps.Timestamp

In [15]:
air["timestamp"].dtypes # It shows type is object, so we convert to date time.

dtype('O')

In [16]:
air["timestamp"] = pd.to_datetime(air["timestamp"])
air["timestamp"].dtypes

dtype('<M8[ns]')

In [17]:
# Handling string data type
cleaned_data["gender"] = cleaned_data["gender"].str.capitalize()
# also have upper() and lower()

In [18]:
cleaned_data["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [19]:
cleaned_data["country"].str.contains("india", case = False) # case false is to ignore case

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object