In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("raw_data.csv")
df.sample()

   id      name   age country gender   income
1   1  John Doe  29.0     USA   Male  55000.0

In [3]:
# apply()
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x: "20%" if x>= 50000 else "10%") # apply() is used to apply a function to values. Here apply is a higher order function meaning
# it takes other functions as arguments.
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [4]:
# map()
gender_map = {"Male" : "M", "Female" : "F", "Unknown" : "U",}
df2["gender"].map(gender_map)

0       M
1       M
2       F
3       U
4       F
5       M
6       F
7       M
8       F
9       M
10    NaN
Name: gender, dtype: object

In [5]:
# assign()
df2.assign(new_income = df2["income"] * 1.1)

    id          name   age country   gender   income  tax  new_income
0    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
1    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN     USA  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0   China     Male  51000.0  20%     56100.0
6    6           NaN  45.0   India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%     63800.0

In [6]:
# replace()
df2["country"].replace("USA", "US")

0         US
1         US
2     Canada
3         US
4      Spain
5      China
6      India
7        NaN
8         US
9     Mexico
10        US
Name: country, dtype: object

In [7]:
# Transforming Data

In [8]:
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [9]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax"] # Renaming columns, you can change the order to change the order of the columns.
df2.rename(columns={"Income": "Salary"})
df2.rename(index={0: "Zero"})

      Id          Name   Age Country   Gender   Income  Tax
Zero   1      John Doe  29.0     USA     Male  55000.0  20%
1      1      John Doe  29.0     USA     Male  55000.0  20%
2      2    Jane Smith   NaN  Canada   Female  62000.0  20%
3      3          Alex   NaN     USA  Unknown  47000.0  10%
4      4  Maria Garcia  34.0   Spain   Female      NaN  10%
5      5        Li Wei  27.0   China     Male  51000.0  20%
6      6           NaN  45.0   India   Female  73000.0  20%
7      7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8      8    Rachel Lee  29.0     USA   Female  62000.0  20%
9      9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10    10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [10]:
df2["Income"] = df2["Income"].fillna(10000)
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())
df2.sort_values("Income")

    Id          Name    Age Country   Gender   Income  Tax
4    4  Maria Garcia  34.00   Spain   Female  10000.0  10%
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0  10%
3    3          Alex  32.75     USA  Unknown  47000.0  10%
5    5        Li Wei  27.00   China     Male  51000.0  20%
0    1      John Doe  29.00     USA     Male  55000.0  20%
1    1      John Doe  29.00     USA     Male  55000.0  20%
10  10   Emily Davis  31.00     USA      NaN  58000.0  20%
2    2    Jane Smith  32.75  Canada   Female  62000.0  20%
8    8    Rachel Lee  29.00     USA   Female  62000.0  20%
7    7    Ahmed Khan  38.00     NaN     Male  68000.0  20%
6    6           NaN  45.00   India   Female  73000.0  20%

In [11]:
df2 = df2.sort_values(["Income", "Age"], ascending = False) # Sorting will happen on basis of income only but if income is ever the same, then age will be the tie breaker
df2

    Id          Name    Age Country   Gender   Income  Tax
6    6           NaN  45.00   India   Female  73000.0  20%
7    7    Ahmed Khan  38.00     NaN     Male  68000.0  20%
2    2    Jane Smith  32.75  Canada   Female  62000.0  20%
8    8    Rachel Lee  29.00     USA   Female  62000.0  20%
10  10   Emily Davis  31.00     USA      NaN  58000.0  20%
0    1      John Doe  29.00     USA     Male  55000.0  20%
1    1      John Doe  29.00     USA     Male  55000.0  20%
5    5        Li Wei  27.00   China     Male  51000.0  20%
3    3          Alex  32.75     USA  Unknown  47000.0  10%
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0  10%
4    4  Maria Garcia  34.00   Spain   Female  10000.0  10%

In [12]:
# df2.sort_index()
# df2.reset_index() It creates a new index column to preserve the original sorting and then gives the data new labels.
# write drop=True in brackets if you want to drop that new column

In [13]:
# Ranking

df2["Ranking"] = df2["Income"].rank() # Created a ranking based on income. If we pass ascending = False in brackets, it'll make 1 the highest ranking. 
# method = dense for having only whole values. min and max for min or max values in case of tie.
df2

    Id          Name    Age Country   Gender   Income  Tax  Ranking
6    6           NaN  45.00   India   Female  73000.0  20%     11.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0  20%     10.0
2    2    Jane Smith  32.75  Canada   Female  62000.0  20%      8.5
8    8    Rachel Lee  29.00     USA   Female  62000.0  20%      8.5
10  10   Emily Davis  31.00     USA      NaN  58000.0  20%      7.0
0    1      John Doe  29.00     USA     Male  55000.0  20%      5.5
1    1      John Doe  29.00     USA     Male  55000.0  20%      5.5
5    5        Li Wei  27.00   China     Male  51000.0  20%      4.0
3    3          Alex  32.75     USA  Unknown  47000.0  10%      3.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0  10%      2.0
4    4  Maria Garcia  34.00   Spain   Female  10000.0  10%      1.0

In [14]:
# new_col_order = [col for col in df2.columns if col != "Id" ] + ["Id"]
# df2.columns = new_col_order
# df2

In [15]:
# To write the data

df2 = df2.sort_values("Name")
df2 = df2.reset_index(drop=True)

df2.to_csv("sorted_data.csv")

In [16]:
# Grouping and functions
df2.groupby("Country")["Income"].mean()

Country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain     10000.0
USA       55400.0
Name: Income, dtype: float64

In [17]:
df2.groupby("Country")["Income"].min()

Country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain     10000.0
USA       47000.0
Name: Income, dtype: float64

In [18]:
df2.groupby("Country")["Income"].agg(["mean", "min", "max"])

            mean      min      max
Country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain    10000.0  10000.0  10000.0
USA      55400.0  47000.0  62000.0

In [19]:
df2.groupby("Country").agg({
    "Income" : "max",
    "Age": "mean",
})

          Income    Age
Country
Canada   62000.0  32.75
China    51000.0  27.00
India    73000.0  45.00
Mexico   45000.0  32.75
Spain    10000.0  34.00
USA      62000.0  30.15

In [20]:
df2.groupby("Country").agg(
    Max_Income = ("Income", "max"),
    Mean_Age = ("Age", "mean"),
)

         Max_Income  Mean_Age
Country
Canada      62000.0     32.75
China       51000.0     27.00
India       73000.0     45.00
Mexico      45000.0     32.75
Spain       10000.0     34.00
USA         62000.0     30.15

In [21]:
# Melt (wide format data to long format) and Pivot(long format to wide format) for Reshaping
# melt(columns we want to keep, ones we want to unpivot/melt into one, new column name, value column name)
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22],
    "tax": [1, 2, 3, 4]
})

df

  country  year  sales  profit  tax
0     USA  2020    100      20    1
1     USA  2021    120      25    2
2   India  2020     90      18    3
3   India  2021    110      22    4

In [22]:
melted_df = df.melt(["country", "year"], ["sales", "profit", "tax"], "metrics", "value" )
melted_df

   country  year metrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax      1
9      USA  2021     tax      2
10   India  2020     tax      3
11   India  2021     tax      4

In [23]:
df2 = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22],
})
melted_df2 = df.melt(
    id_vars=["country", "year"],
    value_vars=["sales", "profit"],
    var_name="metrics",
    value_name="value"
)
melted_df2

  country  year metrics  value
0     USA  2020   sales    100
1     USA  2021   sales    120
2   India  2020   sales     90
3   India  2021   sales    110
4     USA  2020  profit     20
5     USA  2021  profit     25
6   India  2020  profit     18
7   India  2021  profit     22

In [24]:
pivoted_df2 = melted_df2.pivot(index=["country", "year"], 
                 columns="metrics", 
                 values="value")
pivoted_df2

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [25]:
# Merging & Joining Data

df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [26]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [27]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [28]:
# Inner join, only common values in the 'on' column are merged.
pd.merge(df_customers, df_orders, on = "customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [29]:
# Left join, keep all the values in the left column while put NaN in any missing values
pd.merge(df_customers, df_orders, on = "customer_id", how = "left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [30]:
# Right join
pd.merge(df_customers, df_orders, on = "customer_id", how = "right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [31]:
#Keep all, put NaN in any missing values
pd.merge(df_customers, df_orders, on = "customer_id", how = "outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [32]:
# Data Concatenation, stacking dataframes on top of each other (rows) or side by side (columns)

In [34]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["Adam", "Eve", "Bob"]
})

df2 = pd.DataFrame({
    "id": [4, 5, 6],
    "name": ["Charlie", "Fester", "Gilian"]
})
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [35]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [38]:
# row
pd.concat([df1, df2], ignore_index = True) # ignore index to remove the labels which are preserved otherwise and get new labels.

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
3   4  Charlie
4   5   Fester
5   6   Gilian

In [39]:
pd.concat([df1, df2], ignore_index = True, axis = 1)

   0     1  2        3
0  1  Adam  4  Charlie
1  2   Eve  5   Fester
2  3   Bob  6   Gilian